### ISSUE TITLE
C++ templates

### ISSUE THREAD

**Issue by Ayush-D** [likecs/Competitive-Coding#11]
Hi, I had read your templates and found inPos() and outPos() functions, can you please elabrote what are these functions 
                                                                                                                                                              template <typename T> void inPos(T &x)
{
  x = 0; register T c = inchar();
  while(((c<48) || (c>57)) && (c!='-')) c = inchar();
  bool neg = false; if(c == '-') neg = true; 
  for(;c<48 || c>57; c = inchar());
  for(;c>47 && c<58; c = inchar())  x=(x<<3)+(x<<1)+(c-48);
  if(neg)     x = -x;
}
 
template <typename T> void outPos (T n)
{
    T N = n, rev = n, count = 0;
    if (N == 0) { outchar('0'); outchar('\n'); return ;}
    while ((rev % 10) == 0) { count++; rev /= 10;} 
    rev = 0;
    while (N != 0) { rev = (rev<<3) + (rev<<1) + N % 10; N /= 10;}  
    while (rev != 0) { outchar(rev % 10 + '0'); rev /= 10;}
    while (count--) outchar('0');outchar('\n');
}
Thanks

**Comment by likecs** [comment]
These functions are used to get fast input and output as compared to native cin/cout or scanf/printf.

Note it works for int/"long long" data types only.
