### ISSUE TITLE
Sort Algorithm

### ISSUE THREAD

**Issue by aryanc403** [likecs/Competitive-Coding#8]
There are no sort algorithms. Can I add some ?

**Comment by likecs** [comment]
Hi aryanc403,
Yes, most welcome. But please follow the guidelines mentioned before sending any pull request. You can add them to "general" folder in C++14. Create the folder sorting algorithm. 

Just a tip. Add one file which describes the usage of the inbuilt sort function with custom comparator examples. (for example: for a struct object, inbuilt object like pair etc).

**Comment by likecs** [comment]
Also, remember to add the source if you copy code/take help from some else code.
